dist: trusty
sudo: false
language: java
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10
  - oraclejdk-ea
  - openjdk6
  - openjdk7
  - openjdk8
  - openjdk10
  - openjdk11
addons:
  apt:
    packages:
      - openjdk-6-jdk
script: ./gradlew --no-daemon run
